### ISSUE TITLE
Add deployment history and rollback page

### ISSUE THREAD

**Issue by spurtell** [openshift/devcenter#164]
https://blog.openshift.com/introduction-to-deployments-and-rollbacks-on-openshift/

**Comment by corey112358** [comment]
@spurtell  I'll take this one, I'll put it under
Managing Your Applications > Deployments

**Comment by spurtell** [comment]
thanks!

**Comment by corey112358** [comment]
Submitted new PR for this issue (https://github.com/openshift/devcenter/pull/238), let me know if it needs any fixes or whatever.
