### ISSUE TITLE
How to setup PHPMYADMIN into OpenShift

### ISSUE THREAD

**Issue by vstevenphan** [openshift/devcenter#226]
I created scalable app in OpenShift so I can't add phpmyadmin. Then, I tried to upload phpmyadmin sources into php folder in host. Then, I rewrite the name of host and post. However I can't access into phpmyadmin page. Why did this happen, and how can I have phpadmin with scalable app?

**Comment by spurtell** [comment]
Github issues are for content or site issues only, please visit https://help.openshift.com.

That being said - phpmyadmin is not currently available for scalable applications and we'll look to update the docs - https://help.openshift.com/hc/en-us/articles/203728004-phpMyAdmin-and-scalable-applications

**Comment by corey112358** [comment]
@vstevenphan @spurtell 
The other problem with this is that installing your own phpmyadmin would only work if you are using the php cartridge.  It would be much easier for you to download something like MySQL WorkBench (the official MySQL admin tool) in combination with the rhc port forward command to have a GUI to interact with your databases.  I'm not sure it's worth writing up a section in the developer portal for it.

**Comment by arielscarpinelli** [comment]
I don't know what is supposed to be the deal with phpMyAdmin. I've forked the original cartridge, set it as "scalable" and is working perfectly: https://github.com/arielscarpinelli/openshift-scalable-phpmyadmin
