### ISSUE TITLE
investigate i18n

### ISSUE THREAD

**Issue by ryanj** [openshift/devcenter#227]
check with Mateus and document the process for pt-BR

**Comment by ryanj** [comment]
add notes to the README on how to help with translation efforts

**Comment by ryanj** [comment]
Follow up with @caruccio

**Comment by ryanj** [comment]
Found examples of localized content on awestruct: http://arquillian.org/guides/
Sources: https://github.com/arquillian/arquillian.github.com/tree/develop/guides

**Comment by ryanj** [comment]
I tried copying everything from 'en' into a new 'pt-BR' folder, and it caused each of the menu items to be duplicated. :disappointed: 

Next steps might involve:

* [ ] fix the menu listings - one menu item per page (not per page translation)
* [ ] introduce a standard language selector (as a template?)
* [ ] figure out where to link to, if translations don't exist (add a new contributing section to the README?)

**Comment by spurtell** [comment]
Not complete i18n, but Translate widget has been added to site - https://github.com/openshift/devcenter/pull/235

**Comment by ryanj** [comment]
Works for me. Thanks @spurtell
