### ISSUE TITLE
Add overview section for marker files

### ISSUE THREAD

**Issue by corey112358** [openshift/devcenter#237]
Add Markers section to Managing Your Application 
but leave the specifics in the individual language/cartridge sections, and reference them

**Comment by jsvgoncalves** [comment]
https://developers.openshift.com/en/php-markers.html
https://developers.openshift.com/en/tomcat-markers.html
https://developers.openshift.com/en/ruby-markers.html
https://developers.openshift.com/en/python-markers.html
https://developers.openshift.com/en/node-js-project-structure.html#markers
https://developers.openshift.com/en/ruby-markers.html

**Comment by jsvgoncalves** [comment]
Closed with #413
