### ISSUE TITLE
further differentiate the heading sizes

### ISSUE THREAD

**Issue by suspect-zero** [openshift/devcenter#240]
It would make sense to provide a little more difference in size between the headings (=,==,===,===) so that people will be able to nest them correctly and avoid site building errors/warnings.

**Comment by suspect-zero** [comment]
@jsvgoncalves Would you like to take a look at this and see if you can throw something together for it?

**Comment by jsvgoncalves** [comment]
@suspect-zero Sure thing

**Comment by jsvgoncalves** [comment]
`<h1>` and `<h2>` before and after:
![before-h1h2](https://cloud.githubusercontent.com/assets/1872444/10512403/533863a8-7340-11e5-8095-08d6d6bf94f5.png)

![after-h1h2](https://cloud.githubusercontent.com/assets/1872444/10512402/53374266-7340-11e5-95de-09374e1fb246.png)

`<h2>` and `<h3>` before and after:

![before-h2h3](https://cloud.githubusercontent.com/assets/1872444/10512401/53352bb6-7340-11e5-93ab-e47f7ed54788.png)

![after-h2h3](https://cloud.githubusercontent.com/assets/1872444/10512400/53343486-7340-11e5-857b-fd956947c270.png)

**Comment by suspect-zero** [comment]
@jsvgoncalves Those h3's might be a little light and hard to read.  Any other ideas?

**Comment by jsvgoncalves** [comment]
@suspect-zero Updated

![after-h1h2-v2](https://cloud.githubusercontent.com/assets/1872444/10518484/007a5334-7362-11e5-9f94-0946312f5dcc.png)

![after-h2h3-v2](https://cloud.githubusercontent.com/assets/1872444/10518460/e2883b70-7361-11e5-8891-d0da7375b086.png)
