### ISSUE TITLE
The MEAN Stack on OpenShift - Incorrect remote specified

### ISSUE THREAD

**Issue by Ataye** [openshift/devcenter#242]
Section '3. Deploy', 3rd command block states:

```$ git push YOUR_OPENSHIFT_APP_NAME master```

However the default is `openshift` and not `YOUR_OPENSHIFT_APP_NAME`, so it should be corrected to:

```$ git push openshift master```

At least when i followed the instructions (today) this was how my env was set up.

cheers

Update: This page: https://developers.openshift.com/en/node-js-example-meanstack.html

**Comment by corey112358** [comment]
Can you provide a specific link to the page you are referring to so that we make sure to correct it in the right place.

**Comment by Ataye** [comment]
Corey yes, that's the one.

**Comment by spurtell** [comment]
Fixed with https://github.com/openshift/devcenter/pull/245 - thanks!

**Comment by Ataye** [comment]
Just came across another one, last of section 3. Deploy:

https://www.openshift.com/meanstack
