### ISSUE TITLE
Environment Variables in JSON

### ISSUE THREAD

**Issue by kidwm** [openshift/devcenter#243]
How to use Environment Variables in json configuration or node programs?

https://developers.openshift.com/en/databases-mongodb.html

This page should offer more explanations.

**Comment by corey112358** [comment]
@kidwm you should check out this page if you need more information about using environment variables with openshift: https://developers.openshift.com/en/managing-environment-variables.html

It also might be worth searching for more information on stackoverflow, or posting a question on the openshift tag on stackoverflow

**Comment by kidwm** [comment]
Thanks, but I think that adding the link of this document  to 
https://developers.openshift.com/en/databases-mongodb.html
would be better than duplicate JavaScript and Node in
https://developers.openshift.com/en/managing-environment-variables.html

```json
{
  "database": {
    "name": "database",
    "connector": "mongodb",
    "host": "$OPENSHIFT_MONGODB_DB_HOST",
    "port": "$OPENSHIFT_MONGODB_DB_PORT",
    "database": "title",
    "username": "admin",
    "password": "xxxxxxx"
  }
}
```
And I found that it also works in json with this format.

**Comment by spurtell** [comment]
This was closed prematurely - links added with https://github.com/openshift/devcenter/pull/248.
