### ISSUE TITLE
Refresh JBoss Developer Studio article for current version

### ISSUE THREAD

**Issue by mmalina** [openshift/devcenter#252]
The article at https://developers.openshift.com/en/getting-started-installing-jboss-studio.html is pretty outdated - it shows JBDS 5 on the screenshots and says that you need at least java 6.
Current stable version of JBDS is 8.1 and it requires java 7.
The download link at the beginning of the article redirects to https://www.jboss.org/products/devstudio.html which only offers JBDS 7.1.1 or 8.0.0 for download.

This is in contrast to the Eclipse article which talks about Eclipse Luna and JBoss Tools 4.2 which corresponds to JBDS 8.0:
https://developers.openshift.com/en/getting-started-eclipse.html

Feel free to contact me if you need assistance.

**Comment by jsvgoncalves** [comment]
@mmalina Feel like updating this issue?

**Comment by mmalina** [comment]
@jsvgoncalves The current version of JBoss Developer studio is now JBDS 9.0.0, released on October 7. Release blog is here: http://tools.jboss.org/blog/ga-for-mars.html

**Comment by jsvgoncalves** [comment]
@mmalina thanks for the update. cc @jiri-fiala
