### ISSUE TITLE
NodeJs v0.12.0 Cartridge

### ISSUE THREAD

**Issue by ItsLeeOwen** [openshift/devcenter#279]
https://nodejs.org/download/

**Comment by ryanj** [comment]
+1 I'm working on it.  I'll make sure to add some docs on how to use it when it's ready.

**Comment by ryanj** [comment]
For now, you can use `node-0.12` on OpenShift by including the `.openshift` folder from this repo in your project: https://github.com/ryanj/nodejs-custom-version-openshift

**Comment by spurtell** [comment]
There's also https://hub.openshift.com/quickstarts/128-node-js-0-12

**Comment by spurtell** [comment]
I'm going to close this, as it's not a content issue until there is a full Node.js cartridge.
