### ISSUE TITLE
Broken links to Origin documentation

### ISSUE THREAD

**Issue by luciddreamz** [openshift/devcenter#285]
Broken links to Cartridge Developer's guide, located at http://openshift.github.io/documentationoo_cartridge_developers_guide.html, on [managing action hooks](https://developers.openshift.com/en/managing-action-hooks.html) page.

Recommended: update all links currently pointing to openshift.github.io.

**Comment by spurtell** [comment]
Resolved by https://github.com/openshift/devcenter/pull/287
