### ISSUE TITLE
Fix needed for example for Node.js at step 5 at Marketplace Overview

### ISSUE THREAD

**Issue by IvanGaravito** [openshift/devcenter#294]
Hi Guys,
The example given at https://developers.openshift.com/en/marketplace-overview.html#nodejs, getting `process.env.servicePlanId` is `undefined`.

To fix it, needs to be changed to `process.env[servicePlanId]`.

Greetings.

**Comment by ryanj** [comment]
yep - thanks for reporting the issue

**Comment by spurtell** [comment]
Fixed with https://github.com/openshift/devcenter/issues/294
