### ISSUE TITLE
No instructions on how to run BPMS quickstarts with JBoss BPMS cartridge

### ISSUE THREAD

**Issue by alwong-redhat** [openshift/devcenter#300]
I'd like to run the BPMS quickstarts located here http://www.jboss.org//quickstarts/brms/helloworld-bpmsuite/index.html.  After logging into the the shell of the openshift application and cloning the BPMS git repo, I tried running the "Run the Tests" and that failed (tried to execute mvn clean test on all the POM files on the gear instance).   I can't seem to find the instructions on how to move forward on this.  

Also looked at https://developers.openshift.com/en/xpaas-business-process-management-suite.html and https://developers.openshift.com/en/get-involved-extend-openshift.html and it didn't help.

**Comment by spurtell** [comment]
Have you tried https://hub.openshift.com/quickstarts/86-jboss-bpm-suite ?
