### ISSUE TITLE
rhc setup fail with Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by ronen1malka** [openshift/devcenter#301]
Hi,
I am trying to run rhc setup and failing with the following:

C:\Windows\system32>rhc setup
OpenShift Client Tools (RHC) Setup Wizard

This wizard will help you upload your SSH keys, set your application namespace, and check that other programs like Git
are properly installed.

If you have your own OpenShift server, you can specify it now. Just hit enter to use the server for OpenShift Online:
openshift.redhat.com.
Enter the server hostname: |openshift.redhat.com|

You can add more servers later using 'rhc server'.

Login to openshift.redhat.com: *****MASKED*****
Password: ********

OpenShift can create and store a token on disk which allows to you to access the server without using your password. The

key is stored in your home directory and should be kept secret.  You can delete the key at any time by running 'rhc
logout'.
Generate a token now? (yes|no) yes
Generating an authorization token for this client ... lasts 30 days

Saving configuration to C:\Users\ronen\.openshift\express.conf ... done
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/helpers.rb:579:in `executable?': "\x90" to UTF-8 in conversion fr
om Windows-1255 to UTF-8 (Encoding::UndefinedConversionError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/helpers.rb:579:in `block in exe?'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/helpers.rb:578:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/helpers.rb:578:in `any?'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/helpers.rb:578:in `exe?'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/git_helpers.rb:37:in `block in discover_git_executab
le'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/git_helpers.rb:36:in `select'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/git_helpers.rb:36:in `discover_git_executable'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/wizard.rb:627:in `windows_install'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/wizard.rb:432:in `install_client_tools_stage'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/wizard.rb:67:in `block in run'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/wizard.rb:65:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/wizard.rb:65:in `run'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/commands/setup.rb:57:in `run'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/commands.rb:294:in `execute'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/commands.rb:285:in `block (3 levels) in to_commander
'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/commander-4.2.1/lib/commander/runner.rb:421:in `run_active_command'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/command_runner.rb:72:in `run!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/commander-4.2.1/lib/commander/delegates.rb:12:in `run!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/cli.rb:37:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rhc-1.35.3/bin/rhc:20:in `<top (required)>'
        from C:/Ruby193/bin/rhc:23:in `load'
        from C:/Ruby193/bin/rhc:23:in `<main>'

**Comment by corey112358** [comment]
This isn't really a dev center issue, it's an rhc tooling issue.  Please log a bug report at https://bugzilla.redhat.com/describecomponents.cgi?product=OpenShift%20Online for this issue.
