### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by saifAdnan** [openshift/devcenter#309]
I found a mistake in Enviroment Variable page (https://developers.openshift.com/en/node-js-environment-variables.html)

server.listen(server_port, server_ip_address, function(){
  console.log("Listening on " + server_ip_address + ", server_port " + port)
});

port is incorrect variable, it has to be server_port.

so change port to server_port.

  console.log("Listening on " + server_ip_address + ", server_port " + server_port);

OR

  console.log("Listening on " + server_ip_address + ",  " + server_port  + " port")

**Comment by spurtell** [comment]
Fixed with https://github.com/openshift/devcenter/pull/310 - thanks!
