### ISSUE TITLE
WebSockets connection/disconnection with node.js server from remote client

### ISSUE THREAD

**Issue by camillo777** [openshift/devcenter#316]
Hi,
it seems there is an issue connecting from a remote websocket client to a node.js websocket server running on OpenShift.
The server is simple and minimal; I tried changing nodejs libraries, from "socket.io" to "websocket" and the behaviour is the same.
To debug I am using several clients (webscoket.org echo client, jsfiddle client, nodejs client, ...) with the same result.
What is happening is that after the client connects, suddenly the server shut down and close the connection. I have got no "onConnection" message in the logs, no error in the logs (using "rhc tail"), nothing.
Using the same nodejs client locally on the cartridge, it works ok without any disconnection.

This is the server code I am using:
```
var ipaddress = process.env.OPENSHIFT_NODEJS_IP || "127.0.0.1";
var port = process.env.OPENSHIFT_NODEJS_PORT || 8080;
var app = require("express");
var server = require("http").Server(app);
var io = require("socket.io")(server);

var handleClient = function (socket) {
    console.log("connection");
    socket.sendUTF("hello");
    console.log("hello");
};

io.on("connection", handleClient);

console.log("listen: "+ipaddress+" "+port);
server.listen(port, ipaddress);
```

Here You can see that the server suddenly disconnect/close the websocket:
![screen shot 2015-06-11 at 11 23 30](https://cloud.githubusercontent.com/assets/4798456/8103876/6669f97c-102c-11e5-9fdd-0ccfc4cda55a.png)
![screen shot 2015-06-11 at 11 22 32](https://cloud.githubusercontent.com/assets/4798456/8103875/66681134-102c-11e5-8df0-ffef268ea1b7.png)

Can You help me?
Thank you!
Camillo

**Comment by camillo777** [comment]
Same code on Modulus.io is working fine so it is definitely an OpenShift platform related problem.

**Comment by corey112358** [comment]
This is not the correct place to post this issue.  You should try positing it to StackOverflow.

**Comment by camillo777** [comment]
Hi!
I already did post to StackOverflow, but it seems there is no solution.
http://stackoverflow.com/questions/30627235/websockets-on-openshift-do-not-work-with-remote-client
It is definitely a problem of OpenShift platform using the "ws://" protocol.
Exactly same code on "Modulus.io" is working like a charme.
On OpnShift, no matter the library used (socket.io, websocket, ...) no matter the client used (Android, websocket.org echo, jsfiddle, ...) it is connecting and as soon as the connection is on, disconnecting.
I really do not want who to contact in RedHat or OpenShift and I do not want to pay to use OpenShift if there is this bug still opened.
Hope You understand.

Thank you!

Best regards,
Camillo
