### ISSUE TITLE
my war file is initiating but while accessing I am getting 404 error

### ISSUE THREAD

**Issue by talachutla** [openshift/devcenter#317]
http://shareit-talachutla.rhcloud.com/   
Steps . 
I have deleted src n pom.xml files 
i moved ROOT.war to DEF.war 
scp my war to /app-root/runtime/dependencies/jbossews/webapps/rest-1.0.war
restart my app.  but when i hit http://shareit-talachutla.rhcloud.com/v1/ 
 its giving error .. which is actually working in my local mechine ... when initializing application spring contains are not loading...

**Comment by corey112358** [comment]
This is not the correct place for this issue.  Try posting your issue to stackoverflow.com and tag it "openshift"
