### ISSUE TITLE
broken link for tap plugin

### ISSUE THREAD

**Issue by albfan** [openshift/devcenter#319]
After resolve an issue related to tap plugin

https://issues.jenkins-ci.org/browse/JENKINS-28508

and test it correctly on local,I decided to make a regression for version 1.565.3 (actual version for jenkins cartrigde) to test on openshift

https://github.com/albfan/tap-plugin/tree/1.22-BF

I found that apache on openshift refuse to navigate to tap results, but don't know what to tweak to fix this.

Here is an example

https://jenkins-albfan.rhcloud.com/job/git-ignore/lastCompletedBuild/tapTestReport/

broken links are 

https://jenkins-albfan.rhcloud.com/job/git-ignore/lastCompletedBuild/tapTestReport/t%2Ftapout%2Ft0001-exclude.sh-1/

and the like

**Comment by kinow** [comment]
Hi @albfan is there a way that I can try to debug or reproduce this issue? I guess it might be easy to tell whether we need to fix something else in the plug-in or if it's some configuration problem. Thanks

**Comment by albfan** [comment]
Well, is plain to see that

    $ git clone https://github.com/albfan/tap-plugin
    $ cd tap-plugin
    $ git checkout 1.22-BF
    $ mvn hpi:run

runs without problems on jenkins 1.565.3 [see](https://github.com/albfan/tap-plugin/blob/1.22-BF/pom.xml#L31)

So this seems related with openshift jenkins cartrigde

https://hub.openshift.com/quickstarts/98-jenkins-server

which I don't know how to tweak or modify.

Your best approach is:  

1. Create a free openshift account

2. Install rhc

    $ gem install rhc

3. And issue

    $ rhc app create test jenkins

This will create you a jenkins instance (version 1.565.3). From here, install tap plugin from my fork 

    $ mvn clean install
    $ la target/*.hpi
    tap.hpi

openshift jenkins cartrigde comes with git plugin bundled so you can add a test task easily. Just to ease this bored step, this is a simple repo with a tap based testsuite

https://github.com/albfan/git-ignore

Here is what you need to issue on jenkins task (shell command)

https://github.com/albfan/git-ignore/blob/master/.travis.yml#L8 

tap results will be on 

    t/tapout/*.sh

See output on travis ci

https://travis-ci.org/albfan/git-ignore

The example problem: 

https://jj-albfan.rhcloud.com/job/git-ignore/lastCompletedBuild/tapTestReport/t%2Ftapout%2Ft0001-exclude.sh-1/

shows that is apache the part that gets confused for url. If I try an invalid url on local, jenkins shows a dedicated error page (inside jenkins framelayout) not this unrecoverable error.

**Comment by albfan** [comment]
At least I found a way to create a total customize jenkins

https://github.com/albfan/openshift-cartridge-jenkins

you can try it with

    rhc create app myjenkins https://raw.githubusercontent.com/albfan/openshift-cartridge-jenkins/master/metadata/manifest.yml

Now I can tweak completely the deploy, and gived that openshift supports port-forwarding... any recommendations on what to log or debug?

**Comment by albfan** [comment]
Well the problem is simple. On openshift, jenkins runs behind an apache.

my tap output is left on t/tapout/*.sh, and tap plugin convert / to %2f. Thats ok with a normal configuration, but with jetty running behind apache, %2f is translated to / so apache looks for:

https://jenkins-albfan.rhcloud.com/job/git-ignore/lastCompletedBuild/tapTestReport/t/tapout/t0001-exclude.sh-1/

which do not exists.

I have moved test output to a path without / and everything works fine.

See on:
https://jenkins-albfan.rhcloud.com/job/git-ignore/3/tapTestReport/t0001-exclude.sh-1/
