### ISSUE TITLE
Instructions for Flask do not work with Python 3 cartridge

### ISSUE THREAD

**Issue by waqqasdadabhoy** [openshift/devcenter#321]
I created a python3 cartridge and followed the instructions at https://developers.openshift.com/en/python-flask.html

However, it was unable to install Flask, and gave me a 500 Internal Server Error when trying to access the app. Installing Flask using pip over ssh worked, and then the app ran successfully.

I believe this issue may be relevant: https://github.com/jfmatth/openshift-django17/issues/20

**Comment by thesteve0** [comment]
Flask is not recommended with Python 3.

http://flask.pocoo.org/docs/0.10/python3/

**Comment by corey112358** [comment]
Closing due to non-recommendation by the vendor.
