### ISSUE TITLE
Wrong folder path for ssh keys

### ISSUE THREAD

**Issue by dhanvi** [openshift/devcenter#323]
https://developers.openshift.com/en/getting-started-debian-ubuntu.html

In the above link after the line "After creating a configuration file, setup will configure SSH keys so that your system can remotely connect to your applications, including deploying your applications using Git:"

The path of the ssh keys is given as windows one it should have been /home/username/.ssh/id_rsa.pub

the path used is a windows one

**Comment by spurtell** [comment]
Since this is part of a fragment that's included on all OS-specific pages and the actual rhc commands are the same, I added a note wherever the path is displayed as a Windows path. See https://github.com/openshift/devcenter/pull/324
