### ISSUE TITLE
rhc app snapshot save is deprecated

### ISSUE THREAD

**Issue by sordyl** [openshift/devcenter#325]
Need to update https://developers.openshift.com/en/managing-common-rhc-commands.html#

Change "rhc app snapshot save" to "rhc snapshot-save" per:

*$ rhc app snapshot save
Warning: This command is deprecated. Please use 'rhc snapshot-save' instead.*

**Comment by spurtell** [comment]
Resolved by https://github.com/openshift/devcenter/pull/326
