### ISSUE TITLE
Ruby "recommended version" on Windows

### ISSUE THREAD

**Issue by Azolo** [openshift/devcenter#327]
Is it still viable to have Ruby 1.9.3 as the recommended version for Windows?

Now that 1.9.3 has reached EoL I've noticed a lot of gems dropping support for Ruby 1.9.3. Since `rhc` seems to use *optimistic* dependency resolution on a bunch of gems, it just feels like something could break at any time.

On the other hand, if none of the gems stop that support, everything could work just fine.

**Comment by corey112358** [comment]
Thank you for the inquiry/suggestion.

For the time being rhc seems to work well with 1.9.3, but does not work well with 2.2.  We will update the recommended versions when 1.9.3 stops working.

**Comment by Azolo** [comment]
Kk, sounds good. Also RubyInstaller recommends 2.1.X because you are correct 2.2 currently doesn't gave the number of fat gems that 2.1 has.
