### ISSUE TITLE
Typo on Collaboration page

### ISSUE THREAD

**Issue by dobbymoodge** [openshift/devcenter#329]
https://developers.openshift.com/en/managing-collaboration.html

First sentence: "All OpenShift Online plans allow you to **mange** users..."

Should be "manage", I hope.

**Comment by corey112358** [comment]
Submitted https://github.com/openshift/devcenter/pull/333 to fix the typo, even though I prefer the current wording :)

@spurtell Can you take a look at this when you get a chance?

**Comment by corey112358** [comment]
This has been fixed now.  Thanks for reporting it @dobbymoodge
