### ISSUE TITLE
Dead link on Port Binding/Routing page

### ISSUE THREAD

**Issue by dobbymoodge** [openshift/devcenter#330]
Port Binding/Routing page: https://developers.openshift.com/en/managing-port-binding-routing.html

Link for text "Cartridge Developers Guide" points to dead URL: http://www.openshift.org/documentation/oo_cartridge_developers_guide.html#exposing-services-tcp-endpoints

**Comment by corey112358** [comment]
Submitted https://github.com/openshift/devcenter/pull/332 to fix the issue

@spurtell Can you take a look at this when you get a chance?

**Comment by corey112358** [comment]
This has been fixed now, thanks for reporting it @dobbymoodge
