### ISSUE TITLE
broken link in openshift quickstart pages

### ISSUE THREAD

**Issue by oresmus** [openshift/devcenter#337]
a help page in what I am calling your "quickstart pages" (from which i've elided some hex digits (that might be secret) by replacing them with 'hexdigits' below),

    https://openshift.redhat.com/app/console/application/hexdigits-parks/get_started?wizard=true

has this link

    https://www.openshift.com/developers/install-the-client-tools

which apparently redirects to this link

    https://developers.openshift.com/en/getting-started-client-tools.html

which shows me a 404 error message, and has a link for "reporting a content issue"
which goes to

    https://github.com/openshift/devcenter/issues

so I am reporting the above issue here.

(I got to those quickstart pages by clicking on a ribbon "run this on openshift" on a sample app called "parks", and signing up for openshift, and clicking the link to have it show me how to edit code.)

**Comment by coreydaley** [comment]
Thanks for reporting the issue.
Submitted pull request https://github.com/openshift/devcenter/pull/341 to fix this issue

**Comment by spurtell** [comment]
Merged and published.
