### ISSUE TITLE
Creating Drupal 8 Application fails

### ISSUE THREAD

**Issue by MVC013** [openshift/devcenter#339]
I don't seem to be able to install a Drupal 8 Application.

This is what I get :

Stopping Apache server
MySQL 5.1 database added.  Please make note of these credentials:

Connection URL: mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/

You can manage your new MySQL database by also embedding phpmyadmin.
The phpmyadmin username and password will be the same as the MySQL credentials above.

To schedule your scripts to run on a periodic basis, add the scripts to 
your application's .openshift/cron/{minutely,hourly,daily,weekly,monthly}/
directories (and commit and redeploy your application).

Example: A script .openshift/cron/hourly/crony added to your application
         will be executed once every hour.
         Similarly, a script .openshift/cron/weekly/chronograph added
         to your application will be executed once every week.
The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 55dec3507628e15377000039 -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c6,c239' /bin/sh -c \"gear prereceive --init >> /tmp/initial-build.log 2>&1\""' returned an error. rc=255

.Last 10 kB of build output:
Syntax error on line 2 of /var/lib/openshift/55dec3507628e15377000039/php/configuration/etc/conf.d/openshift.conf:
DocumentRoot '/var/lib/openshift/55dec3507628e15377000039/app-root/runtime/repo/php' is not a directory, or is not readable
An error occurred executing 'gear prereceive' (exit code: 1)
Error message: CLIENT_ERROR: Failed to execute: 'control stop' for /var/lib/openshift/55dec3507628e15377000039/php

For more details about the problem, try running the command again with the '--trace' option

**Comment by corey112358** [comment]
This is not the correct place to post an issue like that, you should try posting it to stackoverflow, or a drupal 8 mailing list
