### ISSUE TITLE
App is down - MySql Database Not Responding

### ISSUE THREAD

**Issue by philipchukwuka** [openshift/devcenter#343]
I have an application up on OpenShift which has been working fine up till recently. It's a WordPress app and I have not made any changes on it for months until some days ago it began to show "Error establishing a database connection".

Even trying to open phpMyAdmin gives "#2003 - Can't connect to MySQL server on '127.2.219.130' (111) - The server is not responding."

**Comment by coreydaley** [comment]
This is not the correct place to post this type of issue.  Try checking the "Get Help" section of the developer portal (https://developers.openshift.com/help)
