### ISSUE TITLE
Add docs for "apt-get install rhc" in Debian/Ubuntu

### ISSUE THREAD

**Issue by IvanSanchez** [openshift/devcenter#344]
Related to https://developers.openshift.com/en/getting-started-debian-ubuntu.html:

`rhc` exists as a Debian package in Stable (https://packages.qa.debian.org/r/rhc.html) and in Ubuntu starting from vivid (http://packages.ubuntu.com/vivid/rhc).

The documentation on how to install `rhc` on Debian should reflect this, pointing to the simpler `apt-get install rhc` way of installing the tools.

**Comment by coreydaley** [comment]
Are you interested in writing that up and submitting a pull request?

**Comment by IvanSanchez** [comment]
@coreydaley You mean something like #348? ;-)

Please bear in mind that it's my first time with AsciiDocs (I'm a markdown kind of guy myself).
