### ISSUE TITLE
Add SailsJS on the Cartridge

### ISSUE THREAD

**Issue by dantedantas** [openshift/devcenter#347]
Is possible add SailsJS (https://github.com/balderdashy/sails) on the Cartridge?

When I am trying, I am getting this message: "The cartridge manifest at 'https://github.com/balderdashy/sails' could not be downloaded: The cartridge manifest at 'https://github.com/balderdashy/sails' must be smaller than 20480 bytes."

**Comment by coreydaley** [comment]
The repository that you are referencing does not appear to be a valid cartridge.  Try looking at the cartridge developers guide for more information: https://docs.openshift.org/origin-m4/oo_cartridge_developers_guide.html
