### ISSUE TITLE
Restart jboss 7 in openshift origin 4 in digital ocean

### ISSUE THREAD

**Issue by luispimenta** [openshift/devcenter#351]
Hello everyone.
I did the installation of OpenShift Origin 4 on the Digital Ocean server, and then installed JBossAS 7 this way:

yum install -y https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/tomcat6-6.0.39-1.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/tomcat7-7.0.50-1.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/maven3-3.0.3-4.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/jboss-as7-modules-7.1.1.Final-1.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/jboss-as7-7.1.1.Final-1.noarch.rpm
yum install -y openshift-origin-cartridge-jbossas \
openshift-origin-cartridge-jbossews 
service ruby193-mcollective restart
oo-admin-ctl-cartridge -c import-node --activate
sudo service openshift-broker restart

I create an app jboss 7 and everything works normally after installation, by the time restart the application.

The jboss no longer starts, always generating the following error:

2015/09/15 14:09:42,799 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) JBAS015876: Starting deployment of "ROOT.war"
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000f2168000, 27123712, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 27123712 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/jvm-11423/hs_error.log
~                              

I instaled java 1.7

**Comment by coreydaley** [comment]
This is not the correct place for OpenShift Origin questions, you should try the methods listed on openshift.org for your questions.
