### ISSUE TITLE
Change JBoss Fuse manifest bit.ly links to direct link

### ISSUE THREAD

**Issue by luciddreamz** [openshift/devcenter#352]
The JBoss Fuse example includes bit.ly links referencing an old version of the JBoss Fuse Cartridge manifest.yml file. The bit.ly links should be replaced with: https://raw.githubusercontent.com/jboss-fuse/fuse-openshift-cartridge/master/metadata/manifest.yml

**Comment by coreydaley** [comment]
This should be fixed now.
