### ISSUE TITLE
rhc env-list do not provide list of env variables

### ISSUE THREAD

**Issue by megha-n-bodke** [openshift/devcenter#357]
rhc env-list do not provide list of env variables
```
megha@megha-Latitude-E6230:~/lab$ rhc env-list -a py3
megha@megha-Latitude-E6230:~/lab$ 
```
Where as query through web returns list of variables.
http://py3-lbmegha.rhcloud.com/env

rhc 1.37.1
OS: xubuntu 14.04

**Comment by suspect-zero** [comment]
This is not the correct place for such a request, please try posting your question on one of the stack exchange network sites.

**Comment by megha-n-bodke** [comment]
IMO, this seems to be issue with rhc utility.

**Comment by suspect-zero** [comment]
Correct, that is possibly an issue with the rhc utility, not an issue with the Developer Portal.  You can log a bug report here (https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online) for the issue you are having.

BTW, i believe that the rhc env-list command ONLY lists custom environment variables (those set with the rhc env-set command) and not any environment variables that are associated directly with your application such as mysql/postgresql/mongodb credentials, etc.

That information can be found here (https://developers.openshift.com/en/managing-environment-variables.html#_viewing_custom_environment_variables) in the Developer Portal.

**Comment by megha-n-bodke** [comment]
If it meant for custom variables, then no issues. Good to close.
