### ISSUE TITLE
Changing application - doesn't see the changes

### ISSUE THREAD

**Issue by ArashT-Akelius** [openshift/devcenter#358]
Hello dear all,
I just started to test openshift. So I created a tomcat7 project, made my changes, followed the instruction on how to clone, commit and push the changes. The command line message is "Build Success". But I don't know where to access the new web app I created. I still see the default application provided by openshift. 

My Url : http://tomcat7-arashtaheri.rhcloud.com/

Link to the Source code: https://github.com/spring-projects/spring-mobile-samples/tree/master/archive/java-configuration/lite-device-delegating-view-resolver-jc

Command Line Message:
remote: [INFO] Packaging webapp
remote: [INFO] Assembling webapp [lite-device-delegating-view-resolver-jc] in [/var/lib/openshift/561298180c1e662989000092/app-root/runtime/repo/t                  arget/lite-device-delegating-view-resolver-jc-0.1.0]
remote: [INFO] Processing war project
remote: [INFO] Copying webapp resources [/var/lib/openshift/561298180c1e662989000092/app-root/runtime/repo/src/main/webapp]
remote: [INFO] Webapp assembled in [216 msecs]
remote: [INFO] Building war: /var/lib/openshift/561298180c1e662989000092/app-root/runtime/repo/target/lite-device-delegating-view-resolver-jc-0.1.                  0.war
remote: [INFO] ------------------------------------------------------------------------
remote: [INFO] BUILD SUCCESS
remote: [INFO] ------------------------------------------------------------------------
remote: [INFO] Total time: 1:29.742s
remote: [INFO] Finished at: Mon Oct 05 11:50:08 EDT 2015
remote: [INFO] Final Memory: 17M/98M
remote: [INFO] ------------------------------------------------------------------------
remote: [WARNING] The requested profile "openshift" could not be activated because it does not exist.
remote: Preparing build for deployment
remote: Deployment id is d74f19dc
remote: Activating deployment
remote: Starting jbossews cartridge
remote: Found 127.8.231.1:8080 listening port
remote: -------------------------
remote: Git Post-Receive Result: success
remote: Activation status: success
remote: Deployment completed with status: success
To ssh://561298180c1e662989000092@tomcat7-arashtaheri.rhcloud.com/~/git/tomcat7.git/
   c3a6541..0af10e1  master -> master

**Comment by suspect-zero** [comment]
This is not the correct place to post your issue, you should try posting on StackOverflow.
