### ISSUE TITLE
configuring external SMTP server for emails - Opencart

### ISSUE THREAD

**Issue by Asif-Mahmood** [openshift/devcenter#361]
I have Opencart PHP application deployed on one of the gears. The application sends out emails at certain position like Order creation, customer creation etc. As sendmail is not allowed on openshift, I am trying to connect my external SMTP server on port 465 but it seems the port is blocked. I have tried on 25 port as well with non SSL but same behavior. Openshift states that the ports for external SMTP server are open. can anyone please help me? my server details are following which is running perfectly fine. but the issue is, i am not able to even open connections from openshift, which means ports are blocked. please help.
host: mail.virsacollection.com
port: 465, 25d

**Comment by suspect-zero** [comment]
This is not the correct place for such a request.  Please try posting your issue to one of the stack exchange network sites.
