### ISSUE TITLE
redirecting openshift rhcloud domain to custom domain 

### ISSUE THREAD

**Issue by simran66** [openshift/devcenter#362]
Openshift application url: your-techchick.rhcloud.com
Custom domain: www.yourtechchick.com

I need to redirect from your-techchick.rhcloud.com to yourtechchick.com . I have the Cname set up correctly. I have added the redirection rule in .htaccess.
To avoid duplicate content problems, I tried this redirection.

Here is my .htaccess file:

RewriteEngine On
RewriteBase /

RewriteCond %{HTTP_HOST} != www.yourtechchick.com[NC]
RewriteRule (.*) http://www.yourtechchick.com/$1 [R=301,L]

RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

It gives me redirection loop. It tries to redirect your-techick.rhcloud.com over and over and gives redirection loop error. 

How do I fix this?
![redirects](https://cloud.githubusercontent.com/assets/4191009/10371515/68e650dc-6e01-11e5-92d8-3b2d47ac055f.PNG)

**Comment by suspect-zero** [comment]
This is not really the correct place for such a request.  Please try posting your issue to one of the stackexchange network sites.
