### ISSUE TITLE
Unable to configure redirection to https in wildfly 8.2

### ISSUE THREAD

**Issue by harishkannarao** [openshift/devcenter#369]
Hi Team,
I tried to force all traffic to my application to https in wildfly 8.2 server hosted on openshift. However I can't get it working for my application.

I had created a jboss-web.xml file in src/main/webapp/WEB-INF/ directory
\<jboss-web\>
  \<security-domain\>jboss-web-policy\</security-domain\>
  \<valve\>
    \<class-name\>org.jboss.web.rewrite.RewriteValve\</class-name\>
  \</valve\>
\</jboss-web\>

And I created a rewrite.properties file in src/main/webapp/WEB-INF/ directory
RewriteCond %{HTTP:X-Forwarded-Proto} http
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R,L]

However I was still able to access my application on http. I was not redirected to https

Please advice if I am missing some thing in the configuration?

I don't want to apply this change in web.xml, as it becomes difficult to test my application in local and development environment. The problem is I have to configure a self signed certificate in my local wildfly and my tests (rest client and selenium drivers) are failing because of self signed certificate. 
\<security-constraint\>
  \<web-resource-collection\>
    \<url-pattern\>/*\</url-pattern\>
  \</web-resource-collection\>
  \<user-data-constraint\>
    \<transport-guarantee\>CONFIDENTIAL\</transport-guarantee\>
  \</user-data-constraint\>
\</security-constraint\>

**Comment by jsvgoncalves** [comment]
@harishkannarao the issues on this repository pertain only to the openshift developer center. Please post such questions to community websites such as http://stackoverflow.com/questions/tagged/openshift
