### ISSUE TITLE
Install rubygems is not working for newer version of Ubuntu

### ISSUE THREAD

**Issue by dinhxuanvu** [openshift/devcenter#370]
Link <https://developers.openshift.com/en/getting-started-debian-ubuntu.html#client-tools>

In Ubuntu 14.04.

In Step 2: Install RubyGems : $ sudo apt-get install rubygems is no longer working. Instead, the package rubygems-intergration should be used instead. The command should be sudo apt-get install rubygems-integration.

**Comment by jsvgoncalves** [comment]
@jiri-fiala

**Comment by jsvgoncalves** [comment]
@jiri-fiala What about making the summary a bit more user friendly with link bookmarks? Just as in the **In this Tutorial** section

**Comment by jsvgoncalves** [comment]
@jiri-fiala "and comprises four steps:" should be **three** instead
