### ISSUE TITLE
rhc setup ssh key selection

### ISSUE THREAD

**Issue by ILMostro** [openshift/devcenter#371]
I'm not sure whether this is the proper place to report a bug/feature-request for the `rhc` commandline tool; if not, I offer my apologies and ask for further instructions if available.

In any case, running the `rhc setup` command, as instructed by the openshift website the option to add an SSH key automatically is presented to the user:

```
Your public SSH key must be uploaded to the OpenShift server to access code.  Upload now? (yes|no) yes

  default (type: ssh-rsa)
  -----------------------
    Fingerprint: XX:XX:XX...
    Available: true/false
```
While this is obviously convenient and helpful, I wonder if it might be possible to offer the user a way to specify **which** SSH key will be used/uploaded? The default now is, well, I'm not sure *what* the default is.  Did the script upload all of my ssh keys to the server? I'm not aware of a way to check that at the moment.

**Comment by jsvgoncalves** [comment]
@ILMostro You can try at http://stackoverflow.com/questions/tagged/openshift-client-tools or over at https://github.com/openshift/rhc. The issues on this repository pertain only to the openshift developer center.
