### ISSUE TITLE
Manifest file too big?

### ISSUE THREAD

**Issue by Antronin** [openshift/devcenter#374]
I get the below error when trying to add a custom cartridge:
The cartridge manifest at 'https://github.com/syntaxsugar/openshift-tesseract-cartridge' could not be downloaded: The cartridge manifest at 'https://github.com/syntaxsugar/openshift-tesseract-cartridge' must be smaller than 20480 bytes.

The actual size of the cartridge is 356 Bytes, so the error message is false.

**Comment by jsvgoncalves** [comment]
@Antronin You can try to ask at #openshift on irc, at http://stackoverflow.com/questions/tagged/openshift-cartridge or http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only to the openshift developer center.
