### ISSUE TITLE
Django Rest in Openshift

### ISSUE THREAD

**Issue by PrinceP** [openshift/devcenter#375]
No module named 'django.utils.six.moves.http_client';

Error in log
from rest_framework import viewsets
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]   File "/var/lib/openshift/562d0ea27628e1117100000f/python/virtenv/venv/lib/python3.3/site-packages/djangorestframework-3.2.3-py3.3.egg/rest_framework/viewsets.py", line 26, in <module>
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]     from rest_framework import generics, mixins, views
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]   File "/var/lib/openshift/562d0ea27628e1117100000f/python/virtenv/venv/lib/python3.3/site-packages/djangorestframework-3.2.3-py3.3.egg/rest_framework/generics.py", line 10, in <module>
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]     from rest_framework import mixins, views
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]   File "/var/lib/openshift/562d0ea27628e1117100000f/python/virtenv/venv/lib/python3.3/site-packages/djangorestframework-3.2.3-py3.3.egg/rest_framework/mixins.py", line 10, in <module>
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]     from rest_framework.response import Response
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]   File "/var/lib/openshift/562d0ea27628e1117100000f/python/virtenv/venv/lib/python3.3/site-packages/djangorestframework-3.2.3-py3.3.egg/rest_framework/response.py", line 11, in <module>
[Sat Oct 31 04:20:02 2015] [error] [client 127.10.44.129]     from django.utils.six.moves.http_client import responses

**Comment by jsvgoncalves** [comment]
@PrinceP You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only to the openshift developer center.
