### ISSUE TITLE
rhc ssh looks in wrong place for ssh executable

### ISSUE THREAD

**Issue by otbster** [openshift/devcenter#376]
On my windows git installation (version 2.6.2), "ssh.exe" is located at "C:\Program Files\Git\usr\bin". However the rhc ssh command only checks "C:\Program Files\Git\ssh.exe" and "C:\Program Files\Git\bin\ssh.exe", so does not find it.

Adding "#{base}\\Git\\usr\\bin\\ssh.exe" to the array in 441-452 of ssh_helpers.rb fixes the problem, on rhc version 1.37.1. (this is where rhc ssh creates the paths to check for ssh)

**Comment by jsvgoncalves** [comment]
@otbster You can try at http://stackoverflow.com/questions/tagged/openshift-client-tools or over at https://github.com/openshift/rhc. The issues on this repository pertain only to the openshift developer center.

**Comment by otbster** [comment]
Sorry, thanks for posting it there (I blindly followed a link from the Open Shift homepage here)

**Comment by jsvgoncalves** [comment]
@otbster Can you tell me the page where you found it?

**Comment by otbster** [comment]
For instance on the https://developers.openshift.com/en/troubleshooting-faq.html page, the "Report a Content Issue" link takes you to this github repo
