### ISSUE TITLE
Go here link not working

### ISSUE THREAD

**Issue by gautamkrishnar** [openshift/devcenter#378]
the **go here** link which points to https://www.openshift.com/node/add/quickstart on https://developers.openshift.com/en/get-involved-extend-openshift.html page is not working

Returning a 
# 404!

**Comment by tiwillia** [comment]
Here is the appropriate link: https://hub.openshift.com/quickstarts/new

**Comment by corey112358** [comment]
@jsvgoncalves Can you fix the link on the above page and deploy please?

**Comment by gautamkrishnar** [comment]
Thanks @tiwillia

**Comment by jsvgoncalves** [comment]
@corey112358 @gautamkrishnar Merged and deployed.

**Comment by gautamkrishnar** [comment]
@jason-callaway cool!
