### ISSUE TITLE
OpenShift DIY Cartridge and JRuby + Gem Install Problem

### ISSUE THREAD

**Issue by markosca** [openshift/devcenter#381]
The Step with Quickstart Cartridge

Searching about JRuby and OpenShift give me a result about JRuby "unofficial" quickstart cartridge for OpenShift. Can be found bellow in GitHub
 https://github.com/openshift-quickstart/jruby-openshift-quickstart
The step can be found in above page. Generally, first create an application using DIY cartridge.
Optional, use rhc to add MySQL 5.5 cartridge to the application (additional from me, not in the quickstart). 
Merge source code from above github with  DIY cartridge code.
Commit and push it to OpenShift. As a note here, I am using Eclipse plugin for git and OpenShift operation. This in itself deserve a very long blog. Request in comment if anyone interested.
So right here I got stuck with the same error.
"ERROR:  While executing gem ... (SocketError)"     bind: name or service not known" 

My instinct is that OpenShift, change or add a strict policy about using out bound ports. Base on my initial (manual) effort that fail and the quickstart cartridge that fail with same error. Logically, that quickstart cartridge must work previously. Otherwise it wont be posted on GitHub as a quickstart cartridge for JRuby on OpenShift. 

Back on my earlier comment that OpenShift is a fast evolving cloud platform. Let me throw in another thought. That this is one of the growing pain of OpenSource. Being opensource, information are shared freely. But, when change happened (and those change easily happened very fast), those information are usually not updated.

So back to the drawing board. More searching on the internet and asking question on OpenShift should help. Crossing my finger that this is solvable.

**Comment by jsvgoncalves** [comment]
@markosca You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only the documentation on the openshift developer center.

**Comment by markosca** [comment]
Hi João,

thanks for your reply.
I have a question at stackoverflow (
http://stackoverflow.com/q/29816218/1369791) but I haven't an valid
solution for this issue.

This seems to be a little problem but this doesn't allow me to continue
with a project.

The solution of this problem depends that I can use opensifth or not.

Thanks for your time.

Best regards.
Marcos.





2015-11-11 10:52 GMT+01:00 João Gonçalves <notifications@github.com>:
