### ISSUE TITLE
rhc setup does not work as expected

### ISSUE THREAD

**Issue by juagicre** [openshift/devcenter#383]
In windows 10 and the last ruby and git frameworks installed it fails when executing the rhc setup after installing the rhc gem.
I followed some stackovervflow suggestions like net-ssh reinstalation, downgrade, and so on but they did not work in my case.
Do you expect to update the gem to make it work? Otherwise, what are the other possibilities to configure the git locally to point in our openshift app?
Thanks a lot.

**Comment by jsvgoncalves** [comment]
@juagicre You can try over at #openshift on irc or at https://github.com/openshift/rhc. The issues on this repository pertain only to the openshift developer center.

Also, upon creating a new app the git url is provided, simply use the `git clone` command to fetch the repo.
