### ISSUE TITLE
Unable to cancel dreamfactory subsciption nor able to view dashboard

### ISSUE THREAD

**Issue by m-menon** [openshift/devcenter#386]
was trying to cancel the Dreamfactory subscription and then set it up again. I get this error (shown in the attached screenshot). And it says that the operation was not completed successfully. I cannot view the dash as well
![openshift_dremfactory_dashboard_error](https://cloud.githubusercontent.com/assets/10776430/11329756/d8b670d8-91db-11e5-97ea-4d52e4613d6b.jpg)
![openshift_dremfactory_cancel_subs_error](https://cloud.githubusercontent.com/assets/10776430/11329757/d8ba393e-91db-11e5-8337-07ff7e138845.jpg)

**Comment by jsvgoncalves** [comment]
@m-menon You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only to the openshift developer center.
