### ISSUE TITLE
New Relic add-on is broken/obsolete and should be removed

### ISSUE THREAD

**Issue by brechtm** [openshift/devcenter#388]
Not sure where to report this. New Relic support asked me to raise this issue with OpenShift.

The New Relic add-on available on the OpenShift Marketplace seems to be broken. It creates a new account on New Relic, but when logging into it, I get stuck in an infinite loop (redirecting to AppDirect).

Instead of installing this cartridge, creating a New Relic account manually and simply following the [instructions provided by New Relic](https://docs.newrelic.com/docs/agents/python-agent/hosting-services/python-agent-openshift): gets things running quickly. These instructions are for the Python agent, but I suppose the basic setup is the same for other agents.

To me, it seems the New Relic add-on is broken and obsolete. Can it be removed from the Marketplace to avoid confusing people?

**Comment by corey112358** [comment]
New Relic is in the process of being removed from the Marketplace.  Thank you for reporting the issue.
