### ISSUE TITLE
"rhc setup" doesn't work with Ruby 2.2.3

### ISSUE THREAD

**Issue by jgraden** [openshift/devcenter#389]
On page https://developers.openshift.com/en/getting-started-windows.html#client-tools , under Step 1 - Install Ruby, it says that "If you are not sure which version to install, it is recommended to use the latest 1.9.3 installer.". However, using 2.2.3 results in an error when running "rhc setup" (more details described at http://stackoverflow.com/questions/28896733/rhc-setup-gives-error-no-such-file-dl-import ).

Suggestion: Documentation page should be updated to either statically recommend a version, or add steps to ensure latest version of Ruby can be used.

**Comment by corey112358** [comment]
Can you open a bug report here for that issue: https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online
