### ISSUE TITLE
help with ssh

### ISSUE THREAD

**Issue by tomarone** [openshift/devcenter#390]
I created my keys and installed OK but my system (installing on windows 10) reports at 'rhc ssh myappname' 'No System SSH available. Please use the --ssh option' etc.
I installed Git where should the path to my SSH executable be? everything else is ok so far.

**Comment by tomarone** [comment]
for some reason the 64 bit version's path might not've worked

**Comment by jsvgoncalves** [comment]
@tomarone  You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift-client-tools. The issues on this repository pertain only to the openshift developer center.
