### ISSUE TITLE
Cannot access my web application

### ISSUE THREAD

**Issue by sbourgeois1** [openshift/devcenter#394]
Hello,

Some month ago, I started developing a new application integrating 'redmine' with another system that I continue to develop. 
Today, I wanted to open my app (url: https://redmine-txp.rhcloud.com/), but I got the following message 'This webpage is not available'.
So, I wonder why I have this issue and what I should do... Thanks for any advise.
I am not a 'system' expert, so, it is not easy for me to pla

**Comment by sbourgeois1** [comment]
.. so it is not easy for me to play with system settings. Maybe there is something I misunderstand? Thanks for any support / advise for solving this issue.

**Comment by jsvgoncalves** [comment]
@sbourgeois1 please submit the following form: https://developers.openshift.com/en/contact.html
