### ISSUE TITLE
How can I disable HTTPS?

### ISSUE THREAD

**Issue by icha024** [openshift/devcenter#404]
https://developers.openshift.com/en/troubleshooting-faq.html#_how_can_i_disable_https

The response is irrelavant, still don't know how to disable HTTPS: 
"By default, all applications are accessible via HTTP and HTTPS. You don’t have to do anything differently unless you want to force HTTPS."

**Comment by jsvgoncalves** [comment]
Try this: http://stackoverflow.com/questions/7432809/htaccess-redirect-https-url-to-http

We'll update the docs, thanks.
