### ISSUE TITLE
Compiling Failure because of Missing v8.h in Node.js 0.10.0(Official) and 0.12.0(Community).

### ISSUE THREAD

**Issue by Schezuk** [openshift/devcenter#405]
And /opt/rh/nodejs010/root/usr/include/node/ is not writtable so I have no idea how to fix it.
Moreover, Node.js 0.10.0(Official) will try to write node_modules to somewhere not permitted. 
Node.js 0.12.0(Community) does not, though I have no idea if it is ver 0.12.0 or 0.10.35.

**Comment by jsvgoncalves** [comment]
@Schezuk You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only to the openshift developer center.
