### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jomifanu** [openshift/devcenter#412]
Hi, I'm trying to learn how to manually deploy a precompiled war into my openshift tomcat. I was trying to follow this guide https://www.openshift.com/kb/kb-e1088-how-to-deploy-pre-compiled-java-applications-war-and-ear-files-onto-your-openshift-gear but the links redirect to another page. I'd like where I can find this information. Thanks id advance.

**Comment by jiri-fiala** [comment]
The relevant content can be found ar https://developers.openshift.com/en/tomcat-deployment-options.html
