### ISSUE TITLE
jenkins build errors

### ISSUE THREAD

**Issue by trickpattyFH20** [openshift/devcenter#418]
Been running into some Jenkins build errors. The help page directed me to open an issue here... feels like an odd thing to do since I can't offer exact steps to reproduce the issues.

If I can find the logs I will post them here.

**Comment by jsvgoncalves** [comment]
@trickpattyFH20 which help page are you talking about? The best place to post this is at stackoverflow.com (use the openshift tag) or at https://developers.openshift.com/en/contact.html

**Comment by trickpattyFH20** [comment]
Looks like I clicked on the wrong link. Not sure how I didn't find that form. I'll give that a shot. Thank you. @jsvgoncalves
