### ISSUE TITLE
Add a Markers section to the node docs

### ISSUE THREAD

**Issue by JJ** [openshift/devcenter#432]
For instance, including [this marker found in the blog](https://blog.openshift.com/any-version-of-nodejs-you-want-in-the-cloud-openshift-does-it-paas-style/) and maybe others I haven't been able to find...

**Comment by jsvgoncalves** [comment]
Thanks for contributing @JJ , are you still working on this?

**Comment by JJ** [comment]
I added it in my fork and checked it locally, it mostly works. So, short
answer: yes.

**Comment by JJ** [comment]
Great! Thanks!
