### ISSUE TITLE
Add a section for Yii Framework

### ISSUE THREAD

**Issue by abdlquadri** [openshift/devcenter#434]
I have spent the whole day trying to deploy my Yii application OpenShift, no success.

I am using the advance template. [https://github.com/yiisoft/yii2-app-advanced.git](url) Unfortunately I cant edit conf files as described in the Official Yii Instalation guide. [https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md](url)

If there is a section that describes how to setup Yii on openshift it will increase the adoption of openshift.

**Comment by developercorey** [comment]
If you get Yii framework working on OpenShift Online, please feel free to add a Pull Request to the devcenter about how to get it working.  But at this time we have no plans to add a section as you have described.

**Comment by abdlquadri** [comment]
Great.
