### ISSUE TITLE
Remove outdated blog page

### ISSUE THREAD

**Issue by Download** [openshift/devcenter#436]
Trying to figure out how to upgrade to newer Node version with OpenShift, I turn to Google:
https://www.google.com/#safe=off&q=openshift+upgrade+node

First result:
https://blog.openshift.com/any-version-of-nodejs-you-want-in-the-cloud-openshift-does-it-paas-style/

Unfortunately, this page is outdated. It's referring to a GitHub repo that no longer exists.
Comments are closed on it so I report it here.

**Comment by Download** [comment]
The problem is that it ranks so high in Google

**Comment by developercorey** [comment]
We will get that article updated, in the interim, you can use https://hub.openshift.com/quickstarts/243-node-js-latest to run newer node versions.

**Comment by Download** [comment]
@developercorey Thanks for that pointer!

**Comment by Download** [comment]
@developercorey 
Unfortunately, the original page is still there and it's still referring to a non-existing repo.
