### ISSUE TITLE
What is OpenShift page talks about OpenShift Online

### ISSUE THREAD

**Issue by alberttwong** [openshift/devcenter#447]
https://developers.openshift.com/index.html.  Shouldn't it just talk "what is openshift".

**Comment by jiri-fiala** [comment]
The [devcenter](https://github.com/openshift/devcenter) is dedicated to the OpenShift Online; I believe the current content is relevant.

Please feel free to elaborate in more details what specific content related to the OpenShift platform in general would you expect to be there. (Note that the video introduces the OpenShift as a platform, then moves to the OpenShift Online version.)
