### ISSUE TITLE
"sudo gem install rhc" - Operation not permitted on El Capitan

### ISSUE THREAD

**Issue by joaoreynolds** [openshift/devcenter#448]
I'm not exactly sure if this should be mentioned in the docs - but with El Capitan I had to run `sudo gem install -n /usr/local/bin rhc` to install rhc. If this were in the docs it would have saved me a lot of time.

This is the gist I found that helped: https://gist.github.com/barbietunnie/be53fa6f91573dc8cbb6

**Comment by jsvgoncalves** [comment]
@joaoreynolds thanks for reporting, we'll have a look!
