### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by chromial** [openshift/devcenter#450]
https://www.openshift.com/developers/remote-access#keys

Deploying code changes
OpenShift uses the Git version control system for your source code, and grants you access to it via the Secure Shell (SSH) protocol. In order to upload and download code to your application you need to give us your **public SSH key**. You can upload it within the web console or install the RHC command line tool and run rhc setup to generate and upload your key automatically.

Before you can upload and download code, you need to upload a public key to identify you to our servers. If this is your first time creating a public key** read more about SSH keys and remote access.**

**Comment by jsvgoncalves** [comment]
@chromial thanks for reporting. Can you please specify where is the link at?

**Comment by chromial** [comment]
It's on the page that displays this text:
"Deploying code changes
OpenShift uses the Git version control system for your source code, and grants you access to it via the Secure Shell (SSH) protocol. In order to upload and download code to your application you need to give us your** public SSH key.** You can upload it within the web console or install the RHC command line tool and run rhc setup to generate and upload your key automatically."

It's also here: 

"Before you can upload and download code, you need to upload a public key to identify you to our servers. If this is your first time creating a public key** read more about SSH keys and remote access.**"

When you search for ssh on github most of the pages have that link.

**Comment by chromial** [comment]
this page has it; I have attached a screenshot

https://openshift.redhat.com/app/console/application/546be4b05973ca799e00002f-jbossas

![brokenlink](https://cloud.githubusercontent.com/assets/1315665/14907022/d3cfc3fe-0d90-11e6-9f94-5d1f5e78e137.PNG)

**Comment by jsvgoncalves** [comment]
@chromial Please fill in a bug report over at https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online. The issues on this repository pertain only to the openshift developer center.
