### ISSUE TITLE
Add notice about disallowed characters in domain aliases

### ISSUE THREAD

**Issue by corvidism** [openshift/devcenter#451]
(I have been directed here from Red Hat Bugzilla [and this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1329915))

Openshift Online doesn't allow underscores in aliases, but this constraint doesn't appear in the Docs anywhere. Combined with the unspecific error that's thrown by both the online form and the rhc commandline tool, it makes for a nice long bughunt. 

It should probably appear on [Domain Management and SSL Certificates](https://github.com/openshift/devcenter/blob/be2521cbccd1c15bc83149d79399c4fb511efded/source/managing-your-applications/domains-ssl.adoc). Something like this maybe?

> An alias cannot contain the character "_" (underscore).

(Possibly mentioning other disallowed characters - I've asked the person on the bug request, I'll edit this when they reply).

**Comment by jsvgoncalves** [comment]
@corvidism thanks for reporting. we'll take a look into it and change what's appropriate.
