### ISSUE TITLE
Postgresql does not work with scaled python application

### ISSUE THREAD

**Issue by EdwinRor** [openshift/devcenter#458]
I have tried several times but i cannot get postgresql to work when scaled. SQLite3 still works. What do i need to do to make it work on my scalable server? Do i need to add something to haproxy config?

**Comment by developercorey** [comment]
Try posting your question/issue on one of the stack exchange network of sites.  These issues are for problems with the devcenter itself.

**Comment by EdwinRor** [comment]
Never mind. I wanted to delete this post. It is not scalable.
