### ISSUE TITLE
No wsgi.py in the Flask app used in Flask microframework tutorial

### ISSUE THREAD

**Issue by aviaryan** [openshift/devcenter#459]
https://developers.openshift.com/languages/python/flask.html

The flask app used in the tut is at https://github.com/openshift-quickstart/flask-base . There is no wsgi.py as is mentioned in the subsequent steps of the tutorial.

**Comment by jsvgoncalves** [comment]
@aviaryan thanks for reporting, we'll take a look

**Comment by jiri-fiala** [comment]
The Flask quickstart is meant to be an alternative to creating a Flask app manually in a new Python 2.7 app described in the tutorial.
