### ISSUE TITLE
Failed to execute: 'control start'

### ISSUE THREAD

**Issue by tuyendn-deha** [openshift/devcenter#461]
I don't know why the error occurred 
Just try to add a cartridge to my app by using the manifest 
https://raw.githubusercontent.com/tuyendn-deha/openshift-origin-cartridge-cassandra/master/metadata/manifest.yml

------------------------------
Cassandra 2.0 and later require Java 7u25 or later.
Cassandra 2.2.6 database added.  Please make note of these credentials:

       Username:
       Password:
  Database Name:

Connection URL: jdbc:cassandra://127.3.67.130:19160/
Failed to execute: 'control start' for /var/lib/openshift/55239a0de0b8cde119000059/cassandra

**Comment by jsvgoncalves** [comment]
@tuyendn-deha You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only to the openshift developer center.
