### ISSUE TITLE
Why Config Tomcat for unicode then it lost when restart webapp & create a path root to save image not correct

### ISSUE THREAD

**Issue by khienph** [openshift/devcenter#465]
1. I have a webapp and i using unicode, so that i need config tomcat for unicode: 
path: /var/lib/openshift/..../jbossews/conf/server.xml
<Connector address="127.13.143.1"
               port="8080"
               protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443"   URIEncoding="UTF-8"/>
**but when i'm restart then it** 
<Connector address="127.13.143.1"
               port="8080"
               protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />
2. When i had mkdir path
String strParth = request.getSession().getServletContext()
					.getRealPath("/")+ "\\resources\\images\\"
					+ user+ "\\";
if true then it in directory: https://......rhcloud.com/resources/images/user
but it is: /var/lib/openshift/....../jbossews/null\resources\images\user

i need config it, hope openshift support, Thank a lot
my example: http://ecom-phuphat.rhcloud.com/

**Comment by jiri-fiala** [comment]
@ You can try asking on IRC (#openshift) or at [StackOverflow](http://stackoverflow.com/questions/tagged/openshift). The issues on this repository pertain only to the OpenShift developer center.
