### ISSUE TITLE
Error web-build job Jenkins

### ISSUE THREAD

**Issue by mcvela** [openshift/devcenter#466]
I get this error
"rsync: change_dir#3 "/var/lib/openshift/573ec96f2d52719304000056/app-deployments/2016-06-14_07-37-34.131" failed: No such file or directory (2)"

I don´t why

**Comment by jsvgoncalves** [comment]
@mcvela You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only to the openshift developer center.
