### ISSUE TITLE
Typo in getting started guide

### ISSUE THREAD

**Issue by lhorie** [openshift/devcenter#467]
Reproduction Steps: 

- go to https://developers.openshift.com/languages/nodejs/getting-started.html
- read second paragraph
- markdown syntax for the `/managing-creating-applications.html` link is wrong

Expected: 

`The rhc command-line tool makes it easy to [provision new hosted application environments](/managing-creating-applications.html) - complete with DNS, ssh, and git services.`

Actual:

`The rhc command-line tool makes it easy to /managing-creating-applications.html[provision new hosted application environments] - complete with DNS, ssh, and git services.`

**Comment by jsvgoncalves** [comment]
@lhorie Thanks for reporting
