### ISSUE TITLE
Setting up SSH on linux requires ssh keys to be copied to root folder

### ISSUE THREAD

**Issue by sanketraut** [openshift/devcenter#471]
While setting the openshift repository on my ubuntu linux machine, I had to use sudo for rhc setup. That caused Openshift to search for ssh private keys inside my root folder instead of /user/.ssh folder and was giving permission issues while cloning a repository. This is not mentioned in the article by default and should be made clear while installing client tools. I had copied the .ssh folder from my user directory to /root directory and the rhc commands started working fine after that.

**Comment by jiri-fiala** [comment]
As the `rhc setup` utility has been used under the root user, roots' ssh keys were searched for & the root's public ssh key uploaded to OpenShift. [The Ubuntu OpenShift Online getting started guide](https://developers.openshift.com/getting-started/debian-ubuntu.html) explicitly mentions `sudo` where needed. It looks like the guide does not require updating, so I'm gonna close this issue.

If the `rhc setup` did not work correctly for you when running under your user, please elaborate the issue in more details using of the technical support channels offered [here](https://developers.openshift.com/help.html). Issues reported in this repo pertain only to the OpenShift Online Developer Center itself.
