### ISSUE TITLE
About Storage Problems

### ISSUE THREAD

**Issue by ErrorByError** [openshift/devcenter#479]
I have a problem with storage.
I used free plan. Your documents says every application has 1GB storage. But if me install a ownCloud application, storage is changed to 50GB.
Why? Is application storage is 50GB or the ownCloud has bug or error??? 
And, the "50GB storage" is show in ownCloud Settings.

**Comment by developercorey** [comment]
@ErrorByError This isn't really the correct place to post issues with OpenShift in general, this is more focused on issues with the Developer Portal.  However, that is probably a bug with ownCloud looking at the physical disk that is available vs the actual quota that your account has available.
