### ISSUE TITLE
Registering Isue

### ISSUE THREAD

**Issue by cjTarwireyi** [openshift/devcenter#480]
I registered with  open shift account but after 24 hours i am still placed in the waiting list.

**Comment by jiri-fiala** [comment]
The issues on this repository pertain only to the [OpenShift developer center](https://developers.openshift.com/).

Note that OpenShift Online Next Gen Developer Preview [registration form](https://www.openshift.com/devpreview/register.html) says that you will be provided with access for 30 days "as soon as resources become available". The queue could simply be longer.
