### ISSUE TITLE
Mongoexport/ mongoimport  fail auth 

### ISSUE THREAD

**Issue by MCWEMA** [openshift/devcenter#481]
When trying to mongoexport / mongimport a collection from a Mongodb database that is not named as the app name, mongoexport/ mongoimport fail to authenticate and send fail message as the following:

connected to: 127.7.108.2
assertion: 18 { code: 18, ok: 0.0, errmsg: "auth fails" }

Thanks

**Comment by developercorey** [comment]
You should try submitting this as a bug here: https://bugzilla.redhat.com/describecomponents.cgi?product=OpenShift%20Online

This "issues" section is only for issues with the dev center itself.

**Comment by MCWEMA** [comment]
Thanks for the information
