### ISSUE TITLE
I recently get "Failed to execute: 'control restart'"

### ISSUE THREAD

**Issue by dccarlos** [openshift/devcenter#484]
could not open session

could not open session
Failed to execute: 'control restart' for /var/lib/openshift/51ea30415973ca2d88000333/postgresql
Failed to execute: 'control restart' for /var/lib/openshift/51ea30415973ca2d88000333/jbossas

The system was running correctly. Can you helpme please!?

**Comment by developercorey** [comment]
Issues posted here should be related to the devcenter itself, not the OpenShift Online service.  You can find out more information at developers.openshift.com
