### ISSUE TITLE
Private Project Wiped out

### ISSUE THREAD

**Issue by Vonnie** [openshift/devcenter#487]
Private Project started this month is overlaid with a project with updates from 3yrs ago. It is from angular-seed-openshift or angular-seed from brandanmajeske.
On top of that, it was downloaded to my computer.

This person I did not invite onto my github

github.com/Vonnie

**Comment by coreydaley** [comment]
We do not have any control over github repos.  you would need to contact github support about that.

**Comment by Vonnie** [comment]
Sent a letter to GitHub support. Said they would get back to me. Have not heard from them.

**Comment by Vonnie** [comment]
On a contact form for abuse contact, sent 2. Not yet heard from them.

I have a question of you. Your github source is different from my github
source.

If true, they are both wiped out.

**Comment by Vonnie** [comment]
and, the website has the correct info, but the source not matched.

**Comment by coreydaley** [comment]
we don't have any control over your github repo, there is nothing we can do about it.
