### ISSUE TITLE
Unhandled exception reference #1e7edbe41b381db8c2c4ef6a73b83d11

### ISSUE THREAD

**Issue by She110ck** [openshift/devcenter#490]
Hi everyone.  Django app was 8 months ago. Today site doesn't worked. In web GUI status was unkown. I restarted app and got this. App doesn't work. App status is started.

 
Unhandled exception reference #1e7edbe41b381db8c2c4ef6a73b83d11: The thread #<Thread:0x000000062e5120 aborting> (index=1) did not complete within 30 seconds.

**Comment by jiri-fiala** [comment]
Issues reported in this repository pertain only to the [devcenter](https://developers.openshift.com/) itself. You can report the situation you're facing using the [OpenShift Online support form](https://developers.openshift.com/en/contact.html).

**Comment by She110ck** [comment]
thank you
