### ISSUE TITLE
rhc deployment-list not showing all demployments

### ISSUE THREAD

**Issue by tarekshumaila** [openshift/devcenter#491]
Hi there,

Just did a git push today hoping to fix a minor issue, and I ended up erasing all photo media from my site as I was not using global variables for upload locations. Anyways, I read that I can roll back using rhc deployment list, but that command is only showing me the deployment that caused the problem, one and one only. This is the first git push I do in about a year so I am not quite sure how to go back to previous version.

![screen shot 2016-10-12 at 1 00 36 pm](https://cloud.githubusercontent.com/assets/6101167/19323856/ec2a86fa-907b-11e6-9cdc-3a09d1fd514c.png)

I just want to grab all the media that existed prior to the last git push. Any help to find the previous photos are would be greatly appreciated.

Thanks,
Tarek

**Comment by jiri-fiala** [comment]
@tarekshumaila, you can try asking on IRC (#openshift) or submit the issue using the [OpenShift Online support form](https://developers.openshift.com/en/contact.html). The issues on this repository pertain only to the OpenShift [developer center](https://developers.openshift.com/) itself.

Thank you.
