### ISSUE TITLE
pandas-openshift-django

### ISSUE THREAD

**Issue by MCWEMA** [openshift/devcenter#501]
when trying to import pandas I get this error message

FileExistsError: [Errno 17] File exists (mode 700 != expected mode 755): '/tmp/matplotlib-55dc55070c1e6646170001d0'

This happens from within cronfile.sh
However, it does not happen when working from the root console or from within django app.

Thanks

**Comment by jsvgoncalves** [comment]
@MCWEMA  You can try to ask at #openshift on irc or at http://stackoverflow.com/questions/tagged/openshift. The issues on this repository pertain only to the openshift developer center.

**Comment by MCWEMA** [comment]
This seem like a bug!!

**Comment by jsvgoncalves** [comment]
@MCWEMA Feel free to fill in a bug report over at https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online. Again, the issues on this repository pertain only to the openshift developer center.
